[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
example = "feature: this feature enable customize through config file"
schema = "<type>(<scope>): <message>"
schema_pattern = "(build|ci|docs|feat|fix|perf|refactor|style|test|chore):(\\s.*)"

