repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/commit-check/commit-check
    rev: v0.6.2
    hooks: # support hooks
      - id: check-message
      - id: check-branch
      - id: check-author-name
      - id: check-author-email
